---
title: 5. Week 16 -- Hypotheses, associations
subtitle: Written by Rob Davies
order: 5
---

::: callout-warning
This page is under construction: come back soon
:::

## Week 16: Introduction {#sec-wk16-introduction}

Welcome to your overview of the materials and guidance you will work with in **PSYC122 Week 16**.

We will complete four classes in weeks 16-19.
These classes are designed to help students to revise and put into practice some of the key ideas and skills you have been developing in the first year research methods modules *PSYC121, PSYC123 and PSYC124*.

We will do this in the context of a live research project with potential real world impacts: the **Clearly understood** project.

We will present our PSYC122 lessons in the context of this research project because we think that this *context* will help you to make sense of the data, and to see why we ask you to practice the skills we are teaching.

We will be revisiting some of the ideas and techniques you have seen introduced in previous classes.
This is to give you the opportunity to *revise* and *consolidate* your learning.
We will *extend* your development with some new ideas, to strengthen your skills.

Ultimately, we aim to contribute new findings from the data we will collect together.
These new findings will, we hope, help to make the provision of health advice a bit more useful in future.

### Our learning goals

::: callout-warning
In Week 16, we will ask you to do three things.

- *First*, we will ask you to do a pre-lab activity that involves completing a survey.
- *Second*, we will ask you to do a set of practical tasks in the lab activity that are designed to consolidate your learning on *data visualization*.
- *Third*, we will ask you to think critically about predictions about potential associations between measures of participant attributes and measures of understanding of health information.
:::

Completing the survey will help you to make sense of the numbers you will be working with in the activities.
And it will help to teach you about the challenges of measurement, a key aspect of the scientific thinking skills we will help you to develop.

We will use correlations to test predictions about associations and *thus* answer research questions.

## Lectures {#sec-wk16-lectures}

The lecture material for this week is presented in four short parts.

The lecture is designed to give you an overview of:

1. What we are doing in weeks 16-20, *and* how and why you will develop your critical thinking skills;
2. A summary of the health communication project, and the ideas we assume to develop our hypotheses;
3. How we visualize and think about distributions and associations;
4. And how we use R to estimate and test correlations.

You can view video recordings of the lectures using Panopto, by clicking on the links shown following.

::: callout-tip
Before you go on to the activities, **watch* the lectures:
:::

1. Overview (15 minutes)

```{=html}
<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=219a5ba8-cce8-43e3-afea-afaa010f2d91&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&start=9&interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player"></iframe>
```

2. Thinking critically (11 minutes)

```{=html}
<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=6fd6d7e9-7457-441d-a689-afaa0113f62d&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player"></iframe>
```

3. Thinking about associations in research (22 minutes)

```{=html}
<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=5bbbe88e-b701-4658-b484-afaa011819e3&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player"></iframe>
```

4. Interpreting, reporting and visualizing correlations (11 minutes)

```{=html}
<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=ec9bbeb3-ad95-48e1-a03f-afaa012037f9&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player"></iframe>
```

::: callout-tip
The slides presented in the videos can be **downloaded** in two formats.
:::

- [The slides](data/week16/122-hypotheses-assocations.html) exactly as presented (36 MB). 
- [The slides](data/week16/122-hypotheses-associations-printable-edit.docx) converted to a Word .docx (24 MB). 

The slides were written in R (using Quarto) and are produced as .html documents (like web pages.)

You can download the .html file and click on it to open it in any browser (e.g., Chrome, Safari). The slide images are high quality so the file is quite big.

You can download the .docx file and click on to open as a Word document that you can then edit or add notes to. Converting the slides to a .docx distorts some images but the benefit of conversion is that it makes it easier for you to add your notes to the slides.

## Reading: Links to other classes

We do not provide further reading for this class but you will find it helpful to revise some of the key ideas you have been learning about PSYC122 and in other modules.

- The lectures in *PSYC123* on: the scientific method; reliability and validity; experimental design, especially between-subjects studies; hypothesis testing; and precise hypotheses.
- The lecture in *PSYC122* on correlations. 

## Pre-lab activities {#sec-wk6-prelab-activities}

### Pre-lab activity 1 {#sec-wk6-prelab-activities-1}

In weeks 16-19, we will be working together on a research project to investigate how people vary in their response to health advice.

Completing the project involves collecting responses from *PSYC122* students: **you**.

To enter your responses, we invite you to complete a short survey.

Complete the survey by clicking on the link [here]()

::: callout-tip
In our week 19 class activity, we will analyze the data we collect here.
:::

The survey should take about 20 minutes to complete.
Some people will take less time, and some people might take a little more time.

Taking part in the survey is **completely voluntary**.
You can stop at any time without completing the survey if you do not want to finish it.
If you do not want to do the survey, you can do an alternative activity (see below).

All responses will be recorded completely anonymously.

### Pre-lab activity option {#sec-wk6-prelab-activities-2}

If you do not want to complete the survey, we invite you to read the pre-registered research plan for the *PSYC122 health advice* research project.

[Read the project pre-registration](https://osf.io/p6fsc/)

## Lab activities {#sec-wk6-lab-activities}

### Introduction {#sec-wk6-lab-activities-1-introduction}

We will do our practical lab work to develop your skills in the context of a live research project with potential real world impacts: the **Clearly understood** project.

- Our focus will be on **what makes it easy or difficult for people to understand written health information**.

We encounter written health information all the time: in warnings signs, on medication labels, in clinics when we go to see the doctor, and online when we research things we are worried about.
It is not always easy to understand this information.
The problem is that it is unclear how health information should be communicated.
As psychologists, we can help to improve health communication.

::: callout-important
In these classes, we will complete a research project to answer the research questions:

1. What person attributes predict success in understanding?
2. Can people accurately evaluate whether they correctly understand written health information?
:::

### Get ready {#sec-wk6-prelab-activities-ready}

**Download the data** [122_week16_for_students.zip](data/week16/122_week16_for_students.zip) files folder and upload the contents to the new folder you created in RStudio Server.

The folder includes data files:

- `study-one-general-participants.csv`
- `study-two-general-participants.csv`

and the *code file*:

- `2023-24-PSYC122-w16-how-to.R`

### Lab activity 1 {#sec-wk6-lab-activities-1}

<!-- [inset how to .R guide here] -->

### Lab activity 2 {#sec-wk6-lab-activities-2}

#### Questions {#sec-wk6-lab-activities-1-questions}

## Answers {#sec-wk6-lab-activities-answers}

When you have completed all of the lab content, you may want to check your answers with our completed version of the script for this week. **Remember**, looking at this script (studying/revising it) does not replace the process of working through the lab activities, trying them out for yourself, getting stuck, asking questions, finding solutions, adding your own comments, etc. **Actively engaging** with the material is the way to learn these analysis skills, not by looking at someone else's completed code...

## Online Q&A {#sec-wk6-lab-Q-and-A}

Below is the recording of this week's online Q&A.

```{=html}
```
