---
title: Statistics for Psychologists I
subtitle: "Course coordinators: Tom Beesley, John Towse"
email-obfuscation: javascript
order: 1

#listing:
#  id: links
#  template: ../links.ejs
#  contents: guide.yml
---

# Welcome

Welcome to PSYC121!

The module will ensure that students develop the necessary skills they require to carry out psychological enquiry through the statistical analysis of data. Students will receive lectures on the basic theoretical principles behind introductory statistical analysis techniques in psychological research. Students will receive laboratory classes in which they learn how to handle data and to calculate statistical analyses.

Syllabus Topic Areas:

- Introduction to variables and levels of measurement
- Descriptive statistics (central tendency, variability, zscores)
- Hypothesis testing, the sampling process, and using inferential statistics.


# Course Contacts

|             | Email Address                                                  |
|-------------|----------------------------------------------------------------|
| Tom Beesley | [t.beesley\@lancaster.ac.uk](mailto:t.beesley@lancaster.ac.uk) |
| John Towse  | [j.towse\@lancaster.ac.uk](mailto:j.towse@lancaster.ac.uk)     |
|             |                                                                |
